apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LaxmanaRaoKuna/argocd-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
      labels: # The labels to set on the application namespace
        istio-injection: enabled
    automated:
      selfHeal: true
      prune: true
